name: 🔍 Channel search
description: Ask for help in finding a link to the channel stream.
title: 'Find: '
labels: ['channel search']

body:
  - type: input
    attributes:
      label: Channel ID (required)
      description: Unique channel ID from [iptv-org.github.io](https://iptv-org.github.io/). If you can't find the channel you want in the list, please let us know through this [form](https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&projects=&template=channels_add.yml&title=Add%3A+) before posting your request.
      placeholder: 'BBCAmericaEast.us'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: 'Any additional information that may help find a link to the stream faster?'