name: Update IPTV Repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Menjalankan workflow setiap hari pada tengah malam UTC
  workflow_dispatch: # Memungkinkan menjalankan secara manual

env:
  APP_ID: ${{ secrets.APP_ID }}
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run update script
        run: npm run update

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Automated update' || echo "No changes to commit"
          git push
